parent=base
import=common/keycloak

styles=css/login.css
scripts=

kcButtonClass=btn
kcButtonPrimaryClass=btn-primary
kcButtonLargeClass=btn-lg
kcButtonDefaultClass=btn-default
kcButtonBlockClass=btn-block
kcInputClass=form-control
kcInputWrapperClass=form-group
kcFormGroupClass=form-group
kcLabelClass=control-label
kcLabelWrapperClass=col-sm-2 col-md-2
kcLoginClass=login-pf
kcContentWrapperClass=row
kcLabelWrapperClass=col-md-2 col-sm-2 col-12
kcInputWrapperClass=col-md-10 col-sm-10 col-12
kcFormGroupErrorClass=has-error
kcHtmlClass=login-pf
kcBodyClass=
